"""TASK-408 - the published numbers are generated from a measured artifact, never typed.

The README carried 6.9 / 0.74 / -19.5 (the lab mix that approximates the engine) while the spec
carried 7.10 / 0.75 / -17.8 (the engine itself) for weeks, because both were typed by hand from
different runs. Now one file holds the canonical numbers, this script renders them into the two
documents, and `test_render_evidence.py` fails if a document and the file disagree.

    python render_evidence.py --promote experiments/_lab_scratch/task350.json   # after a real run
    python render_evidence.py --write                                           # rewrite the docs
    python render_evidence.py --check                                           # drift? exit 1

`--promote` copies the measured rows out of an `engine_backtest.py --oos` scratch payload into
`evidence_canonical.json`, keeping the `reference` rows (the v8.4 screener and SPY buy-and-hold,
the comparison baselines) as they stand: those two are not produced by `engine_backtest.py` but
by `experiments/reference_rows.py`, which since 2026-09-08 measures them with the corrected
metric on the engine's own mark grid - so all four published rows carry a ratio AND a Sharpe.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from datetime import date
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

HERE = Path(os.path.dirname(os.path.abspath(__file__)))
REPO = HERE.parent
CANONICAL = HERE / "evidence_canonical.json"
README = REPO / "README.md"
SPEC = HERE / "HYDRA_ALGORITHM_SPEC.md"
BEGIN = "<!-- EVIDENCE:BEGIN generated by render_evidence.py from evidence_canonical.json -->"
END = "<!-- EVIDENCE:END -->"


def load(path: Path = CANONICAL) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def _row(data: dict, key: str) -> dict:
    for r in data["rows"] + data.get("reference", []):
        if r["key"] == key:
            return r
    raise KeyError(f"no row {key!r} in the canonical evidence")


def _fmt(value, digits=2, dash="-") -> str:
    if value is None:
        return dash
    return f"{value:.{digits}f}"


def readme_block(data: dict) -> str:
    """The Spanish evidence paragraph of README.md."""
    eng, lab = _row(data, "engine"), _row(data, "lab_mix")
    v84, spy = _row(data, "screener_v84"), _row(data, "spy_buy_hold")
    p = data["panel"]
    return (
        f"**Objetivo declarado:** retorno por unidad de riesgo, no retorno absoluto. Evidencia "
        f"(simulación con contabilidad ejecutable, {p.get('name_es', p['name'])}, costes "
        f"incluidos): el **motor de "
        f"producción** end-to-end (plan/settle/mark, {eng['cycles']} planes semanales "
        f"{p['first_year']}-{p['last_year']}, {p['task']}) da **{_fmt(eng['ann_net'])} % neto, "
        f"ratio retorno/volatilidad {_fmt(eng['ratio_net_vol'])}, maxDD "
        f"{_fmt(eng['maxdd_net'], 1)} %**, y su **Sharpe real** — restando el T-bill, que corrió "
        f"al {_fmt(eng['rf_ann_pct'])} % anualizado en la muestra — es "
        f"**{_fmt(eng['sharpe_excess'])}**. La mezcla del laboratorio que lo aproxima da "
        f"{_fmt(lab['ann_net'])} / {_fmt(lab['ratio_net_vol'])} / {_fmt(lab['maxdd_net'], 1)} "
        f"(Sharpe {_fmt(lab['sharpe_excess'])}), contra el screener v8.4 solo "
        f"({_fmt(v84['ann_net'], 1)} % / {_fmt(v84['ratio_net_vol'])} / "
        f"{_fmt(v84['maxdd_net'], 1)} %, Sharpe {_fmt(v84['sharpe_excess'])}) y SPY "
        f"comprar-y-mantener ({_fmt(spy['ann_net'], 1)} % / {_fmt(spy['ratio_net_vol'])} / "
        f"{_fmt(spy['maxdd_net'], 1)} %, Sharpe {_fmt(spy['sharpe_excess'])}); estas dos son las "
        f"**líneas de comparación**, no el motor, vienen de la auditoría {v84['source']} y están "
        f"**recomputadas el {v84.get('measured_at', '?')}** con la métrica corregida sobre la misma "
        f"rejilla de marcas ({v84['cycles']} pasos de 5 barras, "
        f"[`experiments/reference_rows.py`](hydra_screener_local/experiments/reference_rows.py)) — "
        f"el maxDD de SPY baja a {_fmt(spy['maxdd_net'], 1)} % porque la auditoría lo había medido "
        f"en otra rejilla. El 10 % neto **no se demuestra**; el universo Russell de producción "
        f"**no está medido** (solo S&P 500). No hay track record: el único registro vivo es el "
        f"ledger de `state/`.\n"
        f"\n"
        f"Estas cifras se generan desde [`evidence_canonical.json`]"
        f"(hydra_screener_local/evidence_canonical.json) con `render_evidence.py` (TASK-408); "
        f"medidas el {data['measured_at']} en `{data['source']['commit']}`."
    )


def spec_block(data: dict) -> str:
    """The canonical table for SPEC 9.5 (English, like the rest of the spec)."""
    p = data["panel"]
    lines = [
        f"Canonical numbers, {p['name']}, {p['first_mark']} -> {p['last_mark']} "
        f"({p['task']}, `{data['source']['script']} {' '.join(data['source']['args'])}`, "
        f"measured {data['measured_at']}):",
        "",
        "| config | cycles | net %/yr | net/vol | Sharpe (excess) | maxDD % |",
        "|---|---|---|---|---|---|",
    ]
    for r in data["rows"]:
        lines.append(
            f"| {r['label']} | {r['cycles']} | **{_fmt(r['ann_net'])}** | "
            f"{_fmt(r['ratio_net_vol'])} | **{_fmt(r['sharpe_excess'])}** | "
            f"{_fmt(r['maxdd_net'], 1)} |"
        )
    # The baselines share the table so the comparison cannot be made against a number nobody
    # measured, and stay unbolded so a reader never mistakes one for the engine's own row.
    for r in data.get("reference", []):
        lines.append(
            f"| _baseline ({r.get('source', 'n/a')} audit):_ {r['label']} | {_fmt(r['cycles'], 0)} | "
            f"{_fmt(r['ann_net'])} | {_fmt(r['ratio_net_vol'])} | {_fmt(r['sharpe_excess'])} | "
            f"{_fmt(r['maxdd_net'], 1)} |"
        )
    eng = _row(data, "engine")
    v84, spy = _row(data, "screener_v84"), _row(data, "spy_buy_hold")
    lines += [
        "",
        f"`net/vol` is `mean/sd * sqrt(periods)` on the NET return - the quantity this project "
        f"published as \"Sharpe\" until 2026-09-08, and not a Sharpe ratio. `Sharpe (excess)` "
        f"subtracts the 13-week T-bill bar by bar (the same series `accrue_interest` uses), which "
        f"ran at {_fmt(eng['rf_ann_pct'])} % annualised over this panel; the two differ by "
        f"{_fmt(eng['ratio_minus_sharpe'])} for the engine (TASK-404).",
        "",
        f"The last two rows are the COMPARISON BASELINES, not the engine: the v8.4 screener alone "
        f"and passive SPY. Both come from the {v84['source']} audit and were re-measured on "
        f"{v84.get('measured_at', '?')} by `{v84.get('measured_by', 'experiments/reference_rows.py')}` "
        f"on this same mark grid, so the "
        f"four rows share a calendar and a risk-free level ({_fmt(spy['rf_ann_pct'])} %). SPY's "
        f"return reproduces the audit at one decimal ({_fmt(spy['ann_net'], 1)} % vs 10.96 %) and "
        f"its ratio comes out one tick higher ({_fmt(spy['ratio_net_vol'])} vs 0.68); its "
        f"published -54.7 % maxDD does not reproduce at all - that figure, and the audit's TEST "
        f"-31.7 %, are the drawdowns of a 5-bar grid starting 2004-01-05, while on the engine's "
        f"grid the drawdown is {_fmt(spy['maxdd_net'], 1)} % (daily series over the same window: "
        f"-55.19 %). Only those two drawdown figures reproduce anywhere; every field of the row "
        f"published here comes from one grid, the engine's.",
    ]
    return "\n".join(lines)


def replace_block(text: str, block: str, where: str) -> str:
    if BEGIN not in text or END not in text:
        raise ValueError(f"{where} has no EVIDENCE markers; add them once by hand")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return f"{head}{BEGIN}\n{block}\n{END}{tail}"


def current_block(text: str) -> str:
    head, rest = text.split(BEGIN, 1)
    body, _ = rest.split(END, 1)
    return body.strip("\n")


def _repo_relative(path: Path) -> str:
    """Repo-relative with forward slashes; an outside path (a tmp dir in a test) stays absolute."""
    try:
        return str(path.resolve().relative_to(REPO.resolve())).replace("\\", "/")
    except ValueError:
        return str(path).replace("\\", "/")


def _git_commit() -> str:
    try:
        out = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=str(REPO),
                             capture_output=True, text=True, timeout=15)
        return out.stdout.strip() or "unknown"
    except Exception:
        return "unknown"


def promote(scratch: Path, out: Path = CANONICAL) -> dict:
    """Lift the measured rows out of an engine_backtest --oos payload."""
    with open(scratch, "r", encoding="utf-8") as f:
        payload = json.load(f)
    if not payload.get("oos"):
        raise ValueError("canonical evidence is the OOS PIT run; this payload is in-sample")
    rows = payload["rows"]
    lab, eng = rows[0], rows[1]
    prev = load(out) if out.exists() else {}
    data = {
        "generated_by": "render_evidence.py --promote",
        "measured_at": str(date.today()),
        "source": {
            "script": "experiments/engine_backtest.py",
            "args": ["--oos"],
            "scratch": _repo_relative(scratch),
            "commit": _git_commit(),
        },
        "panel": {
            "name": "S&P 500 point-in-time panel with delistings",
            "name_es": "panel S&P 500 point-in-time con delistings",
            "first_mark": payload.get("engine_first"),
            "last_mark": payload.get("engine_last"),
            "first_year": str(payload.get("engine_first") or "")[:4],
            "last_year": str(payload.get("engine_last") or "")[:4],
            "task": "TASK-350",
        },
        "rows": [
            {
                "key": "engine",
                "label": "engine production (pair reset)",
                "cycles": eng.get("cycles"),
                "ann_net": eng.get("ann_net"),
                "ratio_net_vol": eng.get("ratio_net_vol"),
                "sharpe_excess": eng.get("sharpe_excess"),
                "maxdd_net": eng.get("maxdd_net"),
                "rf_ann_pct": eng.get("rf_ann_pct"),
                "ratio_minus_sharpe": eng.get("ratio_minus_sharpe"),
            },
            {
                "key": "lab_mix",
                "label": "lab mix T20+ETF equal (audit)",
                "cycles": lab.get("cycles"),
                "ann_net": lab.get("ann_net"),
                "ratio_net_vol": lab.get("ratio_net_vol"),
                "sharpe_excess": lab.get("sharpe_excess"),
                "maxdd_net": lab.get("maxdd_net"),
                "rf_ann_pct": lab.get("rf_ann_pct"),
                "ratio_minus_sharpe": lab.get("ratio_minus_sharpe"),
            },
        ],
        # the reference rows are carried over verbatim, INCLUDING their own measured_at: a new
        # engine run re-dates `measured_at` at the top level, and rendering the baselines from
        # that date would publish "re-measured on <today>" for rows nobody re-measured (found by
        # the TASK-413 falsifiability review).
        "reference": prev.get("reference") or [],
    }
    with open(out, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")
    return data


def check(data: dict | None = None) -> list[str]:
    """Return the documents whose generated block does not match the canonical file."""
    data = data or load()
    problems = []
    for path, block in ((README, readme_block(data)), (SPEC, spec_block(data))):
        text = path.read_text(encoding="utf-8")
        if BEGIN not in text or END not in text:
            problems.append(f"{path.name}: no EVIDENCE markers")
            continue
        if current_block(text).strip() != block.strip():
            problems.append(f"{path.name}: block differs from evidence_canonical.json")
    return problems


def write(data: dict | None = None) -> list[str]:
    data = data or load()
    touched = []
    for path, block in ((README, readme_block(data)), (SPEC, spec_block(data))):
        text = path.read_text(encoding="utf-8")
        new = replace_block(text, block, path.name)
        if new != text:
            path.write_text(new, encoding="utf-8")
            touched.append(path.name)
    return touched


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="TASK-408: render the published evidence")
    ap.add_argument("--promote", metavar="SCRATCH",
                    help="lift measured rows from an engine_backtest --oos payload")
    ap.add_argument("--write", action="store_true", help="rewrite README.md and SPEC 9.5")
    ap.add_argument("--check", action="store_true", help="exit 1 if a document has drifted")
    args = ap.parse_args(argv)

    if args.promote:
        data = promote(Path(args.promote))
        print(f"promoted {len(data['rows'])} measured rows into {CANONICAL.name}")
        for r in data["rows"]:
            print(f"  {r['key']}: {r['ann_net']} net, ratio {r['ratio_net_vol']}, "
                  f"sharpe_excess {r['sharpe_excess']}, maxDD {r['maxdd_net']}")
    if args.write:
        touched = write()
        print("rewrote:", ", ".join(touched) if touched else "nothing (already current)")
    if args.check or not (args.promote or args.write):
        problems = check()
        if problems:
            print("EVIDENCE DRIFT:")
            for p in problems:
                print("  -", p)
            print("run: python render_evidence.py --write")
            return 1
        print("evidence in README.md and SPEC 9.5 matches evidence_canonical.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
