"""
send_hydra_summary.py
Hybrid integration layer for HYDRA Screener.

After running the daily screener, this script:
- Loads the latest history (or a provided watchlist)
- Builds a rich, human + machine readable summary
- Prints it nicely
- Optionally sends it via Discord webhook (if DISCORD_WEBHOOK_URL env var is set)
- Writes a machine-readable JSON to `pine/hydra_last_summary.json` for other tools/bots

Usage:
    python send_hydra_summary.py
    python send_hydra_summary.py --top 10
    DISCORD_WEBHOOK_URL="https://..." python send_hydra_summary.py

Intended to be called at the end of screener.py or via the .bat launcher.
"""

import argparse
import json
import os
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Optional

try:
    import requests  # optional, only used if webhook configured
except ImportError:
    requests = None  # type: ignore


from generate_pine_watchlist import (
    find_latest_history,
    load_recommended_tickers,
    generate_watchlist_string,
)

DEFAULT_TOP = 10
SUMMARY_JSON_PATH = Path("pine") / "hydra_last_summary.json"
SUMMARY_TXT_PATH = Path("pine") / "hydra_last_summary.txt"


def load_latest_history_data(history_dir: Path = Path("history")) -> Optional[Dict]:
    """Load the full data from the most recent history file."""
    try:
        latest = find_latest_history(history_dir)
        with open(latest, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        print(f"[WARN] Could not load latest history: {e}")
        return None


def build_rich_summary(history_data: Dict, top_n: int = DEFAULT_TOP) -> Dict:
    """Build a structured summary dict suitable for Discord / logs / JSON."""
    if not history_data:
        return {"error": "No history data"}

    date = history_data.get("date", "unknown")
    regime = history_data.get("regime", {})
    pillars = history_data.get("pillar_multipliers", {})
    rationale = history_data.get("meta_rationale", "")

    top_candidates = history_data.get("top_candidates", [])
    recommended = [c for c in top_candidates if c.get("recommended")]
    if not recommended:
        recommended = top_candidates[:top_n]

    recommended = recommended[:top_n]

    tickers = [c["ticker"] for c in recommended]
    watchlist_str = generate_watchlist_string(tickers)

    summary = {
        "date": date,
        "generated_at": datetime.now().isoformat(),
        "regime": {
            "score": regime.get("score"),
            "type": regime.get("type"),
            "special_modes": regime.get("special_modes", []),
        },
        "pillars": pillars,
        "rationale": rationale,
        "recommended_count": len(recommended),
        "recommended_tickers": tickers,
        "watchlist_for_pine": watchlist_str,
        "top_details": [
            {
                "rank": c.get("rank"),
                "ticker": c.get("ticker"),
                "composite": round(c.get("composite_score", 0), 4),
                "momentum": round(c.get("momentum", 0), 4),
                "passes_strict": c.get("passes_strict", False),
                "special_modes": c.get("special_modes", ""),
            }
            for c in recommended
        ],
    }
    return summary


def format_for_discord(summary: Dict) -> str:
    """Create a nice Discord message (supports embeds via simple text for now)."""
    lines = []
    lines.append(f"**HYDRA Daily Summary — {summary['date']}**")
    lines.append("")

    reg = summary["regime"]
    lines.append(f"**Regime:** {reg['type']} ({reg['score']})")
    if reg["special_modes"]:
        lines.append(f"**Special Modes:** {', '.join(reg['special_modes'])}")
    lines.append("")

    pillars = summary.get("pillars", {})
    if pillars:
        p_str = " | ".join(f"{k}: {v:.2f}x" for k, v in pillars.items())
        lines.append(f"**Pillars:** {p_str}")
    lines.append("")

    if summary.get("rationale"):
        lines.append(f"**Rationale:** {summary['rationale']}")
        lines.append("")

    lines.append(f"**Recommended ({summary['recommended_count']}):**")
    for d in summary["top_details"]:
        flag = "🟢 STRICT" if d["passes_strict"] else ""
        lines.append(f"  {d['rank']}. **{d['ticker']}** — {d['composite']:.4f} {flag}")

    lines.append("")
    lines.append("**Pine Watchlist (copy-paste):**")
    lines.append(f"```{summary['watchlist_for_pine']}```")

    lines.append("")
    lines.append("_Generated by local HYDRA screener — hybrid Python + TradingView_")

    return "\n".join(lines)


def send_to_discord(webhook_url: str, message: str, summary: Dict) -> bool:
    """Send a message to Discord webhook. Returns True on success."""
    if not webhook_url:
        return False
    if requests is None:
        print("[WARN] 'requests' not installed — cannot send webhook. pip install requests")
        return False

    payload = {
        "content": message[:1900],  # Discord limit safety
        "username": "HYDRA Screener",
        "avatar_url": "https://i.imgur.com/4M34hi2.png",  # optional cute avatar
    }

    try:
        resp = requests.post(webhook_url, json=payload, timeout=10)
        if resp.status_code in (200, 204):
            print("[OK] Sent to Discord webhook")
            return True
        else:
            print(f"[WARN] Discord webhook returned {resp.status_code}: {resp.text[:200]}")
            return False
    except Exception as e:
        print(f"[WARN] Failed to send Discord webhook: {e}")
        return False


def send_to_telegram(bot_token: str, chat_id: str, message: str, summary: Dict) -> bool:
    """Send to Telegram bot. Returns True on success."""
    if not bot_token or not chat_id:
        return False
    if requests is None:
        print("[WARN] 'requests' not installed — cannot send to Telegram. pip install requests")
        return False

    url = f"https://api.telegram.org/bot{bot_token}/sendMessage"
    payload = {
        "chat_id": chat_id,
        "text": message[:4000],  # Telegram limit
        "parse_mode": "Markdown",
        "disable_web_page_preview": True,
    }

    try:
        resp = requests.post(url, json=payload, timeout=10)
        if resp.status_code == 200:
            print("[OK] Sent to Telegram")
            return True
        else:
            print(f"[WARN] Telegram API returned {resp.status_code}: {resp.text[:200]}")
            return False
    except Exception as e:
        print(f"[WARN] Failed to send Telegram: {e}")
        return False


def send_to_generic_webhook(url: str, summary: Dict) -> bool:
    """POST the full summary JSON to a generic webhook (for custom bots, Zapier, etc.)."""
    if not url:
        return False
    if requests is None:
        print("[WARN] 'requests' not installed — cannot send generic webhook. pip install requests")
        return False

    try:
        resp = requests.post(url, json=summary, timeout=10, headers={"Content-Type": "application/json"})
        if resp.status_code in (200, 201, 202, 204):
            print("[OK] Sent to generic webhook")
            return True
        else:
            print(f"[WARN] Generic webhook returned {resp.status_code}: {resp.text[:200]}")
            return False
    except Exception as e:
        print(f"[WARN] Failed to send generic webhook: {e}")
        return False


def save_artifacts(summary: Dict, message: str):
    """Write JSON and TXT artifacts for other tools / manual inspection."""
    SUMMARY_JSON_PATH.parent.mkdir(parents=True, exist_ok=True)

    with open(SUMMARY_JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2, ensure_ascii=False)

    with open(SUMMARY_TXT_PATH, "w", encoding="utf-8") as f:
        f.write(message)

    print(f"[OK] Artifacts saved:")
    print(f"  - {SUMMARY_JSON_PATH}")
    print(f"  - {SUMMARY_TXT_PATH}")


def run_sender(top_n: int = DEFAULT_TOP, history_dir: str = "history", silent: bool = False) -> Dict:
    """Callable version for integration from other scripts (e.g. screener.py).

    Returns the summary dict.
    """
    if not silent:
        print("=== HYDRA Hybrid Summary Sender ===")

    history_data = load_latest_history_data(Path(history_dir))
    if not history_data:
        if not silent:
            print("[ERROR] No history data available. Run the screener first.")
        raise RuntimeError("No history data")

    summary = build_rich_summary(history_data, top_n=top_n)
    message = format_for_discord(summary)

    if not silent:
        print("\n" + "=" * 60)
        print(message)
        print("=" * 60 + "\n")

    save_artifacts(summary, message)

    # Webhooks (optional - Discord, Telegram, generic)
    sent = False
    discord_url = os.environ.get("DISCORD_WEBHOOK_URL") or os.environ.get("HYDRA_DISCORD_WEBHOOK")
    if discord_url:
        sent = send_to_discord(discord_url, message, summary) or sent

    telegram_token = os.environ.get("TELEGRAM_BOT_TOKEN") or os.environ.get("HYDRA_TELEGRAM_BOT_TOKEN")
    telegram_chat = os.environ.get("TELEGRAM_CHAT_ID") or os.environ.get("HYDRA_TELEGRAM_CHAT_ID")
    if telegram_token and telegram_chat:
        sent = send_to_telegram(telegram_token, telegram_chat, message, summary) or sent

    generic_url = os.environ.get("GENERIC_WEBHOOK_URL") or os.environ.get("HYDRA_GENERIC_WEBHOOK")
    if generic_url:
        sent = send_to_generic_webhook(generic_url, summary) or sent

    if not sent and not silent:
        print("[INFO] No webhook env vars set (DISCORD_WEBHOOK_URL, TELEGRAM_BOT_TOKEN+TELEGRAM_CHAT_ID, or GENERIC_WEBHOOK_URL).")
        print("       Set them to enable notifications. Artifacts are always saved locally.")

    if not silent:
        print("\n[OK] HYDRA summary ready for hybrid use (Python → user / webhook → TradingView watchlist)")

    return summary


def main():
    parser = argparse.ArgumentParser(description="Send HYDRA daily summary (hybrid integration)")
    parser.add_argument("--top", type=int, default=DEFAULT_TOP, help="How many recommended to include")
    parser.add_argument("--history-dir", type=str, default="history")
    args = parser.parse_args()

    try:
        run_sender(top_n=args.top, history_dir=args.history_dir, silent=False)
    except Exception as e:
        print(f"[ERROR] {e}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
